### Load Data using Batch Learning

In [1]:
import pandas as pd
import numpy as np
def load_data():
    return pd.read_csv("IMDB Dataset.csv")
data = load_data()
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

### TRAIN TEST SPLIT

In [2]:

from sklearn.model_selection import train_test_split
train_set,test_set = train_test_split(data,random_state=42,test_size=0.2)
# train_set,test_set = data[:40000],data[40000:]

In [3]:
# train2_set["sentiment"].value_counts()

### EDA

In [4]:

train_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     40000 non-null  object
 1   sentiment  40000 non-null  object
dtypes: object(2)
memory usage: 625.1+ KB

In [5]:

train_set["sentiment"].value_counts()

negative    20007
positive    19993
Name: sentiment, dtype: int64

## DATA ANAYLSIS

In [6]:
train_set.iloc[0,0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

## DATA CLEANING

In [7]:
import re
review_1 = re.sub(r'[^\w\s]','',re.sub(r'\d','NUMBER',train_set.iloc[0,0].lower()))
review_1,train_set.iloc[0,1]

('one of the other reviewers has mentioned that after watching just NUMBER oz episode youll be hooked they are right as this is exactly what happened with mebr br the first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordbr br it is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side',
 'positive')

In [8]:
from nltk.stem import PorterStemmer
from collections import Counter
stemmer= PorterStemmer()
words_review_1=Counter([stemmer.stem(i) for i in review_1.strip().split()])
words_review_1.most_common()

[('the', 16),
 ('is', 9),
 ('it', 8),
 ('of', 7),
 ('and', 6),
 ('to', 6),
 ('i', 6),
 ('oz', 5),
 ('with', 5),
 ('for', 5),
 ('that', 4),
 ('as', 4),
 ('violenc', 4),
 ('show', 4),
 ('watch', 3),
 ('be', 3),
 ('thi', 3),
 ('br', 3),
 ('me', 3),
 ('wa', 3),
 ('in', 3),
 ('not', 3),
 ('a', 3),
 ('or', 3),
 ('on', 3),
 ('prison', 3),
 ('forget', 3),
 ('other', 2),
 ('just', 2),
 ('episod', 2),
 ('are', 2),
 ('right', 2),
 ('what', 2),
 ('first', 2),
 ('struck', 2),
 ('citi', 2),
 ('where', 2),
 ('so', 2),
 ('high', 2),
 ('say', 2),
 ('due', 2),
 ('but', 2),
 ('wholl', 2),
 ('inmat', 2),
 ('get', 2),
 ('you', 2),
 ('one', 1),
 ('review', 1),
 ('ha', 1),
 ('mention', 1),
 ('after', 1),
 ('number', 1),
 ('youll', 1),
 ('hook', 1),
 ('they', 1),
 ('exactli', 1),
 ('happen', 1),
 ('mebr', 1),
 ('thing', 1),
 ('about', 1),
 ('brutal', 1),
 ('unflinch', 1),
 ('scene', 1),
 ('which', 1),
 ('set', 1),
 ('from', 1),
 ('word', 1),
 ('go', 1),
 ('trust', 1),
 ('faint', 1),
 ('heart', 1),
 ('timid', 1),
 ('pull', 1),
 ('no', 1),
 ('punch', 1),
 ('regard', 1),
 ('drug', 1),
 ('sex', 1),
 ('hardcor', 1),
 ('classic', 1),
 ('use', 1),
 ('wordbr', 1),
 ('call', 1),
 ('nicknam', 1),
 ('given', 1),
 ('oswald', 1),
 ('maximum', 1),
 ('secur', 1),
 ('state', 1),
 ('penitentari', 1),
 ('focus', 1),
 ('mainli', 1),
 ('emerald', 1),
 ('an', 1),
 ('experiment', 1),
 ('section', 1),
 ('all', 1),
 ('cell', 1),
 ('have', 1),
 ('glass', 1),
 ('front', 1),
 ('face', 1),
 ('inward', 1),
 ('privaci', 1),
 ('agenda', 1),
 ('em', 1),
 ('home', 1),
 ('manyaryan', 1),
 ('muslim', 1),
 ('gangsta', 1),
 ('latino', 1),
 ('christian', 1),
 ('italian', 1),
 ('irish', 1),
 ('moreso', 1),
 ('scuffl', 1),
 ('death', 1),
 ('stare', 1),
 ('dodgi', 1),
 ('deal', 1),
 ('shadi', 1),
 ('agreement', 1),
 ('never', 1),
 ('far', 1),
 ('awaybr', 1),
 ('would', 1),
 ('main', 1),
 ('appeal', 1),
 ('fact', 1),
 ('goe', 1),
 ('wouldnt', 1),
 ('dare', 1),
 ('pretti', 1),
 ('pictur', 1),
 ('paint', 1),
 ('mainstream', 1),
 ('audienc', 1),
 ('charm', 1),
 ('romanceoz', 1),
 ('doesnt', 1),
 ('mess', 1),
 ('around', 1),
 ('ever', 1),
 ('saw', 1),
 ('nasti', 1),
 ('surreal', 1),
 ('couldnt', 1),
 ('readi', 1),
 ('more', 1),
 ('develop', 1),
 ('tast', 1),
 ('got', 1),
 ('accustom', 1),
 ('level', 1),
 ('graphic', 1),
 ('injustic', 1),
 ('crook', 1),
 ('guard', 1),
 ('sold', 1),
 ('out', 1),
 ('nickel', 1),
 ('kill', 1),
 ('order', 1),
 ('away', 1),
 ('well', 1),
 ('manner', 1),
 ('middl', 1),
 ('class', 1),
 ('turn', 1),
 ('into', 1),
 ('bitch', 1),
 ('their', 1),
 ('lack', 1),
 ('street', 1),
 ('skill', 1),
 ('experi', 1),
 ('may', 1),
 ('becom', 1),
 ('comfort', 1),
 ('uncomfort', 1),
 ('viewingthat', 1),
 ('if', 1),
 ('can', 1),
 ('touch', 1),
 ('your', 1),
 ('darker', 1),
 ('side', 1)]

### Preparing Data for ML ALGORITHMS

In [9]:

from sklearn.preprocessing import OrdinalEncoder
encoder= OrdinalEncoder()
train_set[["sentiment"]]  =encoder.fit_transform(train_set[["sentiment"]])
test_set[["sentiment"]]=encoder.transform(test_set[["sentiment"]])
encoder.categories_

C:\Users\USER\AppData\Local\Temp\ipykernel_1220\2358869484.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_set[["sentiment"]]  =encoder.fit_transform(train_set[["sentiment"]])
C:\Users\USER\AppData\Local\Temp\ipykernel_1220\2358869484.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_set[["sentiment"]]=encoder.transform(test_set[["sentiment"]])

[array(['negative', 'positive'], dtype=object)]

In [10]:
train_set.head(3)

                                              review  sentiment
0  One of the other reviewers has mentioned that ...        1.0
1  A wonderful little production. <br /><br />The...        1.0
2  I thought this was a wonderful way to spend ti...        1.0

In [11]:

train_set_final = train_set.drop("sentiment",axis=1)
train_set_label = train_set[["sentiment"]].to_numpy().ravel()
test_set_final = test_set.drop("sentiment",axis=1)
test_set_label = test_set[["sentiment"]].to_numpy().ravel()

In [12]:

from sklearn.base import BaseEstimator,TransformerMixin
from scipy.sparse import csr_matrix
class Vectorizer(BaseEstimator,TransformerMixin):
    def __init__(self,size=1000):
        self.vocab_size=size
    def fit(self,X,y=None):
        GodCounter=Counter()
        PrevGodCounter=Counter()
        counters = self.get_counters(X)
        for i in counters:
            for word,count in i.most_common():
                PrevGodCounter[word]+=count
        for word,count in PrevGodCounter.most_common():
            GodCounter[word]=count
        self.vocab = {word:i for i,(word,count) in enumerate(GodCounter.most_common()[:self.vocab_size])}
        return self
    def transform(self,X,y=None):
        rows =[]
        data=[]
        cols=[]
        for row,i in enumerate(self.get_counters(X)):
            for word,count in i:
                rows.append(rows)
                cols.append(self.vocab.get(word,0))
                data.append(count)
        return csr_matrix((data,(rows,cols)),shape=(len(X),self.vocab_size+1))
    def get_counters(self,X):
        counters = []
        for j in range(len(X)):
            procces_i=re.sub(r'[^\w\s]','',re.sub(r'\d','NUMBER',X.iloc[j,0].lower()))
            counter = Counter([stemmer.stem(i) for i in procces_i.strip().split()])
        return counters

In [13]:

vectorizer = Vectorizer()
train_set_transformed = vectorizer.fit_transform(train_set_final)

In [14]:
train_set_transformed

<40000x1001 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

### Training the Models

In [15]:
train_set_transformed[2]

<1x1001 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [19]:

from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier(SVC(C=1000,probability=True),
                          n_estimators=2,algorithm="SAMME.R",learning_rate=0.5)

In [20]:

model.fit(train_set_transformed,train_set_label)

AdaBoostClassifier(base_estimator=SVC(C=1000, probability=True),
                   learning_rate=0.5, n_estimators=2)

In [21]:

from sklearn.metrics import confusion_matrix
y_pred=model.predict(train_set_transformed)
confusion_matrix(train_set_label,y_pred)

array([[20007,     0],
       [19993,     0]], dtype=int64)

In [22]:
model.predict_proba(train_set_transformed[2])

array([[0.5, 0.5]])